### ISSUE TITLE
Add rubocop gem

### ISSUE THREAD

**Issue by NaumenkoSergiy** [dKotetunov/TasksManager#39]
https://github.com/bbatsov/rubocop

Для простоты поменяешь в корне файл .rubocop.yml на

```
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'Gemfile'
    - 'spec/support/**/*'
Metrics/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/MutableConstant:
  Enabled: false
```

Разберись для чего гем и попробуй пофиксить ошибки, что он выдаст о твоем проекте
